---
apiVersion: network.openperouter.io/v1alpha1
kind: Underlay
metadata:
  name: underlay-control-plane
  namespace: openshift-openperouter
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: multi-homing-ctlplane-0.maiqueb.org
  asn: 64514
  tunnelEndpoint:
    cidrs:
      - 100.65.0.0/24
  neighbors:
    - asn: 64512
      address: 192.168.122.15
  interfaces:
    - type: CNIDevice
      cniDevice:
        type: RawConfig
        interfaceName: net1
        rawConfig:
          cniVersion: "1.0.0"
          name: macvlan-underlay
          plugins:
            - type: macvlan
              master: br-ex
              mode: bridge
              capabilities:
                mac: true
              ipam:
                type: dhcp
        runtimeConfig:
          mac: "aa:bb:cc:bb:cc:aa"
