service integrated-vtysh-config

log stdout debug
log timestamp precision 3

debug zebra events
debug zebra vxlan
debug bgp zebra
debug zebra events
debug zebra vxlan
debug bgp zebra
debug zebra events
debug zebra nht
debug zebra kernel
debug zebra rib
debug zebra nexthop
debug bgp neighbor-events
debug bgp updates
debug bgp keepalives
debug bgp nht
debug bgp zebra
debug bfd network
debug bfd peer
debug bfd zebra


vrf $VRF
 vni $L3VNI
exit-vrf

router bgp $ASN vrf red
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit

router bgp $ASN
 no bgp ebgp-requires-policy
 no bgp network import-check
 no bgp default ipv4-unicast

 neighbor $NEI_IP peer-group
 neighbor $NEI_IP remote-as 64514
 neighbor $NEI2_IP peer-group
 neighbor $NEI2_IP remote-as 64514

 bgp listen range $NEI_CIDR peer-group $NEI_IP
 bgp listen range $NEI_CIDR peer-group $NEI2_IP

 !
 address-family ipv4 unicast
  network $VTEP_CIDR
  neighbor $NEI_IP activate
  neighbor $NEI2_IP activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor $NEI_IP activate
  neighbor $NEI_IP allowas-in origin
  neighbor $NEI2_IP activate
  neighbor $NEI2_IP allowas-in origin
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
exit
!


