---
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: L3VNI
metadata:
  name: ${VRF}-${L3VNI}
spec:
  vrf: $VRF
  vni: $L3VNI
---
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: L2VNI
metadata:
  name: ${VRF}-${L2VNI}
spec:
  vrf: $VRF
  vni: $L2VNI
  l2gatewayips:
    - $L2VNI_GW_CIDR
  hostmaster:
    linuxBridge:
      name: $L2VNI_BRIDGE
    type: linux-bridge
