---
apiVersion: v1
kind: Secret
metadata:
  name: vm-ssh-key
type: Opaque
data:
  key: "$SSH_PUBLIC_KEY"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: $VM1_NAME
spec:
  runStrategy: Always
  template:
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: vm-ssh-key
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - evpn-workload
            topologyKey: kubernetes.io/hostname
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
          - disk:
              bus: virtio
            name: os
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            macAddress: 02:79:38:33:33:33
            model: virtio
            name: evpn
            state: up
      networks:
      - pod: {}
        name: default
      - multus:
          networkName: $VNI_BR_NAD_NAME
        name: evpn
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:v1.7.0
        name: os
      - cloudInitNoCloud:
          networkData: |
            ethernets:
              id0:
                match:
                  macaddress: '02:79:38:33:33:33'
                addresses:
                  - $VM1_IP
                gateway4: $VMS_GW
            version: 2
        name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: $VM2_NAME
spec:
  runStrategy: Always
  template:
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: vm-ssh-key
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - evpn-workload
            topologyKey: kubernetes.io/hostname
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
          - disk:
              bus: virtio
            name: os
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            macAddress: 02:79:38:55:55:55
            model: virtio
            name: evpn
            state: up
      networks:
      - pod: {}
        name: default
      - multus:
          networkName: $VNI_BR_NAD_NAME
        name: evpn
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:v1.7.0
        name: os
      - cloudInitNoCloud:
          networkData: |
            ethernets:
              id0:
                match:
                  macaddress: '02:79:38:55:55:55'
                addresses:
                  - $VM2_IP
                gateway4: $VMS_GW
            version: 2
        name: cloudinitdisk
