apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brvni110
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
        ipv4:
          dhcp: false
          enabled: false
        name: brvni110
        state: up
        type: linux-bridge
