---
apiVersion: openpe.openperouter.github.io/v1alpha1
kind: Underlay
metadata:
  name: underlay
spec:
  asn: 64514
  tunnelEndpoint:
    cidrs:
      - 100.65.0.0/24
  neighbors:
    - asn: 64512
      address: 192.168.10.130
  nics: [ "ens4" ]
